UI/Controllers/FeatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO.DTO_Feature;
using BAL.Security;

namespace UI.Controllers
{
    [Authorize]
    public class FeatureController : Controller
    {

        BAL_Feature ftr = new BAL_Feature();
        BAL_Status status = new BAL_Status();

        public ActionResult Index()
        {
            try
            {
                ViewBag.FeaturesAndActions = (List<DTO_GetAll>)Session["FeaturesAndActions"];
                ViewBag.FeatureList = ftr.GetAll();
                var Stat = status.GetAll();
                ViewBag.StatusList = new SelectList(Stat, "Status_Id", "Status_Title");
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public JsonResult Add(DTO_Add feature)
        {
            try
            {
               
                DTO.DTO_User.DTO_GetAll user = (DTO.DTO_User.DTO_GetAll)Session["UserData"];
                feature.InsertedBy = (int)user.id;
                string result = ftr.Add(feature);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpPost]
        public ActionResult Delete(DTO_Delete feature)
        {
            try
            {
                string result = ftr.Delete(feature);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);

            }
        }

        [HttpPost]
        public ActionResult Update(DTO_Update feature)
        {
            try
            {
                DTO.DTO_User.DTO_GetAll user = (DTO.DTO_User.DTO_GetAll)Session["UserData"];
                feature.UpdatedBy = (int)user.id;
                string result = ftr.Update(feature);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult Display(int id)
        {
            try
            {
                return Json(ftr.GetById(id), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult Search(string SearchTerm)
        {
            try
            {
                List<DTO_GetAll> result = ftr.Search(SearchTerm);
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (System.Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult GetAll()
        {
            try
            {
                List<DTO_GetAll> result = ftr.GetAll();
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (System.Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult SideBar()
        {
            try
            {
                List<DTO_GetAll> sidebar;
                if (Request.IsAuthenticated)
                {
                    sidebar = (List<DTO_GetAll>)Session["FeaturesAndActions"];
                }
                else
                {
                    BAL_Feature ftr = new BAL_Feature();

                    sidebar = ftr.GetAll();
                }
                return PartialView(sidebar);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

    }
}

UI/Views/Shared/_Layout.cshtml
@{ 
    DTO.DTO_User.DTO_GetAll user = new DTO.DTO_User.DTO_GetAll();
    
        user = (DTO.DTO_User.DTO_GetAll)Session["UserData"];
    

}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title</title>

    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- Morris -->
    <link href="~/Content/css/plugins/iCheck/custom.css" rel="stylesheet">

    <link href="~/Content/css/plugins/chosen/bootstrap-chosen.css" rel="stylesheet">

    <link href="~/Content/css/plugins/morris/morris-0.4.3.min.css" rel="stylesheet">

    <link href="~/Content/css/animate.css" rel="stylesheet">
    <link href="~/Content/css/style.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">
        <!--SideBar-->

        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <img alt="image" class="rounded-circle" src="~/Content/img/profile_small.jpg" />
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="block m-t-xs font-bold"> @user.UserName.ToString() </span>
                                <span class="text-muted text-xs block">Art Director <b class="caret"></b></span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li><a class="dropdown-item" href="#">Profile</a></li>
                                <li><a class="dropdown-item" href="#">Contacts</a></li>
                                <li><a class="dropdown-item" href="#">Mailbox</a></li>
                                <li class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="~/Home/Logout">Logout</a></li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            IN+
                        </div>
                    </li>
                        @Html.Action("SideBar", "Feature")
                </ul>
            </div>
        </nav>
        <!--Sidebar End-->



        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" action="#">
                            <div class="form-group">
                                <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                </nav>
            </div>


            @RenderBody()
        </div>

        <!-- Mainly scripts -->
        <script src="~/Scripts/js/jquery-3.1.1.min.js"></script>
        <script src="~/Scripts/js/popper.min.js"></script>
        <script src="~/Scripts/js/bootstrap.js"></script>
        <script src="~/Scripts/js/plugins/metisMenu/jquery.metisMenu.js"></script>
        <script src="~/Scripts/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

        <!-- Flot -->
        <script src="~/Scripts/js/plugins/flot/jquery.flot.js"></script>
        <script src="~/Scripts/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
        <script src="~/Scripts/js/plugins/flot/jquery.flot.spline.js"></script>
        <script src="~/Scripts/js/plugins/flot/jquery.flot.resize.js"></script>
        <script src="~/Scripts/js/plugins/flot/jquery.flot.pie.js"></script>
        <script src="~/Scripts/js/plugins/flot/jquery.flot.symbol.js"></script>
        <script src="~/Scripts/js/plugins/flot/curvedLines.js"></script>

        <!-- Peity -->
        <script src="~/Scripts/js/plugins/peity/jquery.peity.min.js"></script>
        <script src="~/Scripts/js/demo/peity-demo.js"></script>

        <!-- Custom and plugin javascript -->
        <script src="~/Scripts/js/inspinia.js"></script>
        <script src="~/Scripts/js/plugins/pace/pace.min.js"></script>
        <script src="~/Scripts/js/plugins/chosen/chosen.jquery.js"></script>
        <script src="~/Scripts/js/plugins/iCheck/icheck.min.js"></script>

        <!-- jQuery UI -->
        <script src="~/Scripts/js/plugins/jquery-ui/jquery-ui.min.js"></script>
        <script src="~/Scripts/js/plugins/select2/select2.full.min.js"></script>
        <!-- Jvectormap -->
        <script src="~/Scripts/js/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js"></script>
        <script src="~/Scripts/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>

        <!-- Sparkline -->
        <script src="~/Scripts/js/plugins/sparkline/jquery.sparkline.min.js"></script>

        <!-- Sparkline demo data  -->
        <script src="~/Scripts/js/demo/sparkline-demo.js"></script>

        <!-- ChartJS-->
        <script src="~/Scripts/js/plugins/chartJs/Chart.min.js"></script>
        <script src="~/Scripts/js/plugins/sweetalert/sweetalert.min.js"></script>

        <script>
            $(document).ready(function () {


                var d1 = [[1262304000000, 6], [1264982400000, 3057], [1267401600000, 20434], [1270080000000, 31982], [1272672000000, 26602], [1275350400000, 27826], [1277942400000, 24302], [1280620800000, 24237], [1283299200000, 21004], [1285891200000, 12144], [1288569600000, 10577], [1291161600000, 10295]];
                var d2 = [[1262304000000, 5], [1264982400000, 200], [1267401600000, 1605], [1270080000000, 6129], [1272672000000, 11643], [1275350400000, 19055], [1277942400000, 30062], [1280620800000, 39197], [1283299200000, 37000], [1285891200000, 27000], [1288569600000, 21000], [1291161600000, 17000]];

                var data1 = [
                    { label: "Data 1", data: d1, color: '#17a084' },
                    { label: "Data 2", data: d2, color: '#127e68' }
                ];
                $.plot($("#flot-chart1"), data1, {
                    xaxis: {
                        tickDecimals: 0
                    },
                    series: {
                        lines: {
                            show: true,
                            fill: true,
                            fillColor: {
                                colors: [{
                                    opacity: 1
                                }, {
                                    opacity: 1
                                }]
                            },
                        },
                        points: {
                            width: 0.1,
                            show: false
                        },
                    },
                    grid: {
                        show: false,
                        borderWidth: 0
                    },
                    legend: {
                        show: false,
                    }
                });

                var lineData = {
                    labels: ["January", "February", "March", "April", "May", "June", "July"],
                    datasets: [
                        {
                            label: "Example dataset",
                            backgroundColor: "rgba(26,179,148,0.5)",
                            borderColor: "rgba(26,179,148,0.7)",
                            pointBackgroundColor: "rgba(26,179,148,1)",
                            pointBorderColor: "#fff",
                            data: [48, 48, 60, 39, 56, 37, 30]
                        },
                        {
                            label: "Example dataset",
                            backgroundColor: "rgba(220,220,220,0.5)",
                            borderColor: "rgba(220,220,220,1)",
                            pointBackgroundColor: "rgba(220,220,220,1)",
                            pointBorderColor: "#fff",
                            data: [65, 59, 40, 51, 36, 25, 40]
                        }
                    ]
                };

                var lineOptions = {
                    responsive: true
                };


                var ctx = document.getElementById("lineChart").getContext("2d");
                new Chart(ctx, { type: 'line', data: lineData, options: lineOptions });

            });
            function ShowMessage(alertclass, MessageText) {
                $('#Message').removeClass();
                $('#Message').addClass(alertclass);
                $('#Message').text(MessageText).fadeIn();
                setTimeout(function () { $('#Message').empty().fadeOut(1000); }, 4000);
            }
            function UpdateButton(FunctionName, ClassName, Text) {
                $("#Button").removeAttr();
                $("#Button").attr("onclick", FunctionName);
                $("#Button").removeClass();
                $("#Button").addClass("btn " + ClassName + " btn-block btn-rounded");
                $("#Button").text(Text);
            }
        </script>

</body>
</html>